In [1]:
from ch33tah.core import Ch33tah, Ch33tahRetest
from ch33tah.dataset import Dataset
import numpy as np
import json

''' lets make some data '''
def makedata(r):
  X = np.random.rand(r, 3)
  y = np.sign(2*X[:,0] - 5*X[:,1] + 3*X[:,2])
  y = np.expand_dims(y, axis=1)
  X = np.hstack((X, y))
  return X

X = makedata(2000)

print("Data, ", X.shape)
print(X, end='\n', sep='\n\n')

Data,  (2000, 4)
[[ 4.17022005e-01  7.20324493e-01  1.14374817e-04 -1.00000000e+00]
 [ 3.02332573e-01  1.46755891e-01  9.23385948e-02  1.00000000e+00]
 [ 1.86260211e-01  3.45560727e-01  3.96767474e-01 -1.00000000e+00]
 ...
 [ 6.70183139e-01  9.73577973e-01  4.65108735e-01 -1.00000000e+00]
 [ 1.04017062e-01  2.41474170e-02  8.81300204e-01  1.00000000e+00]
 [ 2.61910196e-02  9.50827989e-01  5.69917642e-01 -1.00000000e+00]]


In [2]:
''' setup the ch33tah stuff and run it, then save the models. While its running, check the console 
output. youll see  lots of jumbled output like $ 1 2 START, meaning that the first hyperparameter 
set is starting training on the 2nd CV fold. you should see jumbled output where multiple (hp, cv) 
sets are going at the same time. if not please check out an issue! 

results is a big dictionary mapping 
      { model name: 
             {"model": sklearn obj, "avg_performance": float},
       ... }
'''

core = Ch33tah(X, 3, 'classification', 'exampleTest')
results = core.ch33t()
print(list(results.keys()))
bucket_name = core.save_models(results)
print(bucket_name)

['SGDClassifier', 'Perceptron', 'DecisionTreeClassifier', 'LinearSVC', 'XGBClassifier', 'SVC']
exampletest-classification-3135011583


In [3]:
''' ... some time later, reload the models and see how we perform on test data '''
core_rt = Ch33tahRetest('exampletest-classification-3134879021')
models = core_rt.load_models()
print(list(models.keys()))
print()

X2 = makedata(2000)
X2 = Dataset(X2, 3)

eval_res = core_rt.evaluate_test_set(X2)
for model, res in eval_res.items():
  print(model)
  print("\t", res['predictions'])
  print("\t", res['performance'])

['DecisionTreeClassifier', 'LinearSVC', 'Perceptron', 'SGDClassifier', 'SVC', 'XGBClassifier']

DecisionTreeClassifier
	 [-1. -1.  1. ...  1. -1.  1.]
	 {'accuracy': 0.9525}
LinearSVC
	 [-1. -1.  1. ...  1. -1.  1.]
	 {'accuracy': 0.9685}
Perceptron
	 [-1. -1.  1. ...  1. -1.  1.]
	 {'accuracy': 0.9955}
SGDClassifier
	 [-1. -1.  1. ...  1. -1.  1.]
	 {'accuracy': 0.9895}
SVC
	 [1. 1. 1. ... 1. 1. 1.]
	 {'accuracy': 0.5015}
XGBClassifier
	 [-1.  1.  1. ... -1. -1.  1.]
	 {'accuracy': 0.9015}
